### PR TITLE
Removes popup floating, keeps styles. Fixes #71

### LINKED ISSUE #71: Bottom of long details gets hidden
## Issue Overview

When a shelter has a lot of details, the popup content goes off the bottom of the screen. Since you can't drag the popup in any way, there's no way to reveal those details.

## Steps to Reproduce

1. Click on a shelter with a lot of details

## Expected Behavior

To be able to drag or move or scroll something to see all the details

## Possible Solution

Change back to the old way of doing it.

### PR DESCRIPTION
**Pull request by plocket**
## Description

Fixes issue #71

Keeps the fly popup style, but puts the popup back in the map so the bottom doesn't get irreparably cut off.

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [x] I want my code added to the response theme.

### CODE REVIEW

**Comment by plocket** [comment]
@miklb , @omnilord : This ready to merge? If so, I'll be able to move on to the 'null' issue.

**Comment by miklb** [comment]
I am working on re-organizing the javascript in a branch now I'll be sending a PR soon. I'm not changing any of the code, just moving it into `.js` files and then minifying before inlining into the template at build as an include. Just wanted to give a heads up the structure might change and make for a difficult rebase. I'm rebasing your changes into my branch as they are merged.

**Comment by plocket** [comment]
@miklb : Sounds good. Should I hold off on the 'null' change until that's settled down?

**Comment by miklb** [comment]
Might make life easier editing those files. Also, if you have suggestions for js linting now would be a good time to share them. I’m not touching coding style in source.

**Comment by plocket** [comment]
I'll try to find my old linting package.json configurations. I think there were some for css too...

**Comment by plocket** [comment]
Well, here's one that I think is close to what we used that you'd put in `.eslintrc.json`. You might not like some of these. It's pretty strict about some things. You can also put nothing in "rules" and use the default eslint settings.

They're all warnings so they don't block PRs. Linted code is nice, but it doesn't need to stop forward progress. We set it up to lint automatically just before commit was run and that would fix anything that was easily fixable. For more complex stuff, someone would have to deal with it manually if it was really a problem.

``` js
{
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "env": {
    "browser": true
  },
  "extends": "react-app",
  "plugins": [
    "babel",
    "react"
  ],
  "rules": {
    "array-bracket-newline": ["warn", { "multiline": true }],
    "array-bracket-spacing": ["warn", "always"],
    "array-element-newline": ["warn", "always"],
    "arrow-body-style": ["warn", "always"],
    "arrow-parens": ["warn", "always"],
    "babel/no-invalid-this": 1,
    "babel/semi": 1,
    "comma-dangle": ["warn", "always-multiline"],
    "computed-property-spacing": ["warn", "always"],
    "curly": ["warn", "all"],
    "eol-last": ["warn", "always"],
    "indent": ["warn", 2, { "VariableDeclarator": { "var": 2, "let": 2, "const": 3 } }],
    "key-spacing": ["warn", { "align": "value" }],
    "keyword-spacing": ["warn", { "before": true, "after": true }],
    "max-statements-per-line": ["warn", { "max": 1 }],
    "object-curly-newline": ["warn", { "multiline": true }],
    "object-curly-spacing": ["warn", "always", { "arraysInObjects": false, "objectsInObjects": false }],
    "object-property-newline": ["warn", { "allowAllPropertiesOnSameLine": true }],
    "quotes": ["warn", "single", { "allowTemplateLiterals": true }],
    "space-in-parens": ["warn", "never"],
    "space-infix-ops": ["warn"],
    "no-var": ["warn"]
  }
}
```

Types of things I think you might need in your package.json (doesn't automatically lint):

``` js
{
  "scripts": {
    "lint": "./node_modules/.bin/eslint src --fix"
  },
  "devDependencies": {
    "eslint": "4.19.1",
    "eslint-plugin-babel": "5.1.0",
    "eslint-plugin-jest": "21.15.1"
  }
}
```

**Pull request merged**
