### PR TITLE
Ignores changes in built css files (keeps the ones in source)

### PR DESCRIPTION
**Pull request by plocket**
## Description

Did not make an issue

Right now, every build changes the built css files and those changes aren't ignored. That means they show up in status and get added unintentionally all the time. This should fix that.

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] This pull request relates to a ticket.
- [x] This code is tested.
- [x] I want my code added to the response theme.

### CODE REVIEW

**Comment by miklb** [comment]
We can't delete those files. This is a Jekyll theme and the response sites read directly from those CSS files.

**Comment by plocket** [comment]
So I check their changes in every time?

**Comment by plocket** [comment]
I just figured it would build them when it ran on the server.

**Comment by plocket** [comment]
The answer is yes, do commit all built changes caused by source code changes. Don't commit changes made by `watch` when switching branches.

**Pull request closed without merging**
