### PR TITLE
Homepage shelter popup on top. Must hand-test for integration with style changes in #48.

### PR DESCRIPTION
**Pull request by plocket**
## Description

Addresses issue #37

**Must be hand-tested with new popup style changes PR**

On the home page, this should make the shelter popup sit on top of everything else. More visible, especially on mobile phones.

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [?] (Maybe with new styles) Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested. (With master branch)
- [x] I want my code added to the response theme.

### CODE REVIEW

**Comment by miklb** [comment]
@plocket do you want me to resolve the conflicts or would you like to do it?

**Comment by nihonjinrxs** [comment]
@plocket As with #30, I think if you re-pull master to your fork and re-push the branch on the fork, it might get rid of the docs commit [8638b5a](https://github.com/hurricane-response/response-theme/pull/30/commits/8638b5a7dbef85dbaf5a50f2db9ca5d455459404) here.

**Comment by plocket** [comment]
I'll either fix the conflicts or make a new branch with the same changes.

**Comment by plocket** [comment]
Replaced by #49 .

**Pull request closed without merging**
