### PR TITLE
Find me/search on narrow device. Addresses #21.

### PR DESCRIPTION
**Pull request by plocket**
## Description

Addresses issue #21

## List of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] This pull request relates to a ticket.
- [ ] This code is tested. (How to test css?)
- [x] I want my code added to the response theme.

### CODE REVIEW

**Comment by miklb** [comment]
Looks like this picked up a bad commit & has the other PRs in it. Let me know if I can help isolate it.

**Comment by nihonjinrxs** [comment]
@plocket Can you re-pull master to your fork and re-push the branch on the fork? I think that might get rid of the docs commit [8638b5a](https://github.com/hurricane-response/response-theme/pull/30/commits/8638b5a7dbef85dbaf5a50f2db9ca5d455459404)

**Comment by plocket** [comment]
I will do a thing.

**Comment by plocket** [comment]
Bah, I'll just do it over.

**Comment by plocket** [comment]
Replaced by #47

**Pull request closed without merging**
